name: Deploy staging
run-name: 'Deploy staging'

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  pull-requests: write

concurrency:
  group: deploy-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code-checks:
    name: '🔍 Run code quality checks'
    uses: nightstem/site/.github/workflows/run-code-checks.yml@main
    secrets: inherit

  build-and-deploy:
    name: '🚀 Build and deploy to staging'
    environment: staging
    needs: run-code-checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build project
        uses: nightstem/site/.github/actions/build-project@main
        env:
          NEXT_PUBLIC_ENVIRONMENT: staging
          NEXT_PUBLIC_FEATURE_FLAG_HOST: ${{ vars.NEXT_PUBLIC_FEATURE_FLAG_HOST }}
          NEXT_PUBLIC_FEATURE_FLAG_CLIENT_KEY: ${{ vars.NEXT_PUBLIC_FEATURE_FLAG_CLIENT_KEY }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean staging helpers
        run: |
          rm -f out/robots.txt
          rm -f out/sitemap.xml
          mv out/robots.staging.txt out/robots.txt

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: nightstem/site/.github/actions/deploy-cloudflare@main
        with:
          environment: staging
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          build-output-directory: ${{ secrets.BUILD_OUTPUT_DIRECTORY }}
          project-name: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
